version: "3.9"
services:
  collect-target-metabolomics-study:
    build:
      context: .
  nginx:
    image: nginx:1.17
    volumes:
      - ./nginx_conf/nginx.conf:/tmp/nginx.conf
      - ./nginx_conf/htpasswd:/etc/nginx/.htpasswd
      - ./nginx.log:/var/log/nginx
    ports:
      - "80:80"
    env_file:
      - ./nginx_conf/nginx.env
    command: /bin/bash -c "envsubst < /tmp/nginx.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"